/**
 * Test fixtures for QR code verification
 *
 * These are example QR code data structures for testing purposes.
 * In production, these would be generated by the Aura holder app.
 */

import type { QRCodeData } from '../qr/types';

/**
 * Generate a mock QR code data object
 */
export function createMockQRCodeData(overrides: Partial<QRCodeData> = {}): QRCodeData {
  const now = Math.floor(Date.now() / 1000);

  return {
    v: '1.0',
    p: `pres_${generateRandomId()}`,
    h: 'did:aura:mainnet:abc123def456',
    vcs: ['vc_age_21_12345'],
    ctx: {
      show_age_over_21: true,
    },
    exp: now + 300, // 5 minutes from now
    n: Math.floor(Math.random() * Number.MAX_SAFE_INTEGER),
    sig: generateMockSignature(),
    ...overrides,
  };
}

/**
 * Encode QR code data to the aura:// URL format
 */
export function encodeQRCodeData(data: QRCodeData): string {
  const json = JSON.stringify(data);
  const base64 = Buffer.from(json).toString('base64');
  return `aura://verify?data=${base64}`;
}

/**
 * Valid QR code for 21+ age verification
 */
export const VALID_AGE_21_QR = encodeQRCodeData(
  createMockQRCodeData({
    vcs: ['vc_age_21_test123'],
    ctx: {
      show_age_over_21: true,
    },
  })
);

/**
 * Valid QR code for 18+ age verification
 */
export const VALID_AGE_18_QR = encodeQRCodeData(
  createMockQRCodeData({
    vcs: ['vc_age_18_test456'],
    ctx: {
      show_age_over_18: true,
    },
  })
);

/**
 * Valid QR code for verified human
 */
export const VALID_HUMAN_QR = encodeQRCodeData(
  createMockQRCodeData({
    vcs: ['vc_human_test789'],
    ctx: {},
  })
);

/**
 * Expired QR code (presentation expired)
 */
export const EXPIRED_QR = encodeQRCodeData(
  createMockQRCodeData({
    exp: Math.floor(Date.now() / 1000) - 3600, // 1 hour ago
  })
);

/**
 * QR code with invalid signature
 */
export const INVALID_SIGNATURE_QR = encodeQRCodeData(
  createMockQRCodeData({
    sig: 'invalid_signature_data',
  })
);

/**
 * QR code with missing required fields
 */
export const MALFORMED_QR_MISSING_FIELDS = 'aura://verify?data=' +
  Buffer.from(JSON.stringify({ v: '1.0' })).toString('base64');

/**
 * Completely invalid QR code
 */
export const INVALID_QR_NOT_BASE64 = 'aura://verify?data=not-valid-base64!!!';

/**
 * QR code with wrong protocol
 */
export const WRONG_PROTOCOL_QR = 'https://example.com/verify?data=abc123';

/**
 * Raw base64 data (without aura:// prefix)
 */
export const RAW_BASE64_QR = Buffer.from(
  JSON.stringify(createMockQRCodeData())
).toString('base64');

/**
 * QR code for revoked credential (for mocked tests)
 */
export const REVOKED_CREDENTIAL_QR = encodeQRCodeData(
  createMockQRCodeData({
    vcs: ['vc_revoked_test'],
  })
);

/**
 * QR code with multiple credentials
 */
export const MULTI_CREDENTIAL_QR = encodeQRCodeData(
  createMockQRCodeData({
    vcs: ['vc_age_21_test', 'vc_human_test', 'vc_kyc_test'],
    ctx: {
      show_age_over_21: true,
      show_full_name: false,
    },
  })
);

/**
 * QR code with full disclosure
 */
export const FULL_DISCLOSURE_QR = encodeQRCodeData(
  createMockQRCodeData({
    vcs: ['vc_kyc_full_test'],
    ctx: {
      show_full_name: true,
      show_age: true,
      show_age_over_21: true,
      show_city_state: true,
    },
  })
);

// Helper functions

function generateRandomId(): string {
  return Math.random().toString(36).substring(2, 15);
}

function generateMockSignature(): string {
  // Generate a mock 64-byte Ed25519 signature (hex encoded = 128 chars)
  const bytes = new Uint8Array(64);
  for (let i = 0; i < 64; i++) {
    bytes[i] = Math.floor(Math.random() * 256);
  }
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

/**
 * Mock verification result for testing
 */
export const MOCK_VERIFICATION_RESULT = {
  isValid: true,
  holderDID: 'did:aura:mainnet:abc123def456',
  verifiedAt: new Date(),
  vcDetails: [
    {
      vcId: 'vc_age_21_test123',
      vcType: 3, // VC_TYPE_AGE_OVER_21
      status: 2, // VC_STATUS_ACTIVE
      isValid: true,
      isExpired: false,
      isRevoked: false,
      issuedAt: new Date('2025-01-01'),
      expiresAt: new Date('2026-01-01'),
    },
  ],
  attributes: {
    is_over_21: true,
    is_over_18: true,
  },
  auditId: 'audit_test_12345',
  networkLatency: 150,
  verificationMethod: 'online' as const,
};

/**
 * Mock failed verification result
 */
export const MOCK_FAILED_VERIFICATION_RESULT = {
  isValid: false,
  holderDID: 'did:aura:mainnet:abc123def456',
  verifiedAt: new Date(),
  vcDetails: [],
  attributes: {},
  verificationError: 'Credential has been revoked',
  auditId: 'audit_failed_12345',
  networkLatency: 120,
  verificationMethod: 'online' as const,
};
